### ISSUE TITLE
Logic for Randomly generated numbers

### ISSUE THREAD

**Issue by SirPhemmiey** [mattflow/sudoku-solver#6]
Hi, great work on providing this solver library. 

Just one question/request - how can i get the code used for generating the random numbers on the puzzle board? Would appreciate if you can poiint me to the right location or snippet. 

Looking forward to it. 

Thanks.

**Comment by mattflow** [comment]
Hey @SirPhemmiey,

Thanks for the kind words. I am assuming you are talking about the sudoku puzzles on the webpage. I do not have code to generate those. I use a JSON file which holds a large number of puzzles. That file is https://github.com/mattflow/sudoku-solver/blob/gh-pages/src/components/sudokus.json and you can feel free to use it if you like.

There seem to be some good generator libraries out there. A popular one looks to be https://github.com/robatron/sudoku.js (I haven't used it, I just found it through searches).

Hope this helps!

**Comment by SirPhemmiey** [comment]
Hey @mattflow , that helps, thanks so much.
